### ISSUE TITLE
System packages

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/kbsecret#3]
KBSecret currently "supports" packaging for Debian (`.deb`), Arch, and Red Hat (`.rpm`) via [fpm](https://github.com/jordansissel/fpm), but these generated packages are of dubious quality and are almost certainly broken in some form or other.

It would be nice to get first-class packages for these targets (and any others). If you have any experience with packaging, please let me know!

**Comment by woodruffw** [comment]
Added a Homebrew formula here: https://github.com/kbsecret/homebrew-kbsecret

**Comment by Celti** [comment]
After poking at the pacman package generation, it seems that a key issue is that bundle overrides `$GEM_HOME` when building — which of course is what lets it *find* fpm — but fpm relies on `$GEM_HOME` (or at least `gem env gemdir`) to put the package contents in the appropriate location. This unfortunately *can't* be genuinely cross-platform without modification, because Arch and Debian at the least have different defaults for `$GEM_HOME`.

You *should* be able to fix this with liberal application of fpm's `--prefix` and `--gem-bin-path` flags. `--gem-bin-path "/usr/bin"` and `--prefix "/usr/lib/ruby/gems/2.5.0"` seem to generate perfectly usable pacman packages for current Arch Linux (there are a couple of issues with them containing files that would normally be stripped, and using numeric ownership instead of symbolic in the tar, but they install and run just fine).

**Comment by woodruffw** [comment]
Thanks for the info!

I was actually planning on getting rid of the `fpm` packages pretty soon -- they're more or less completely broken on Debian, don't provide manpages, etc. Now that I know they (can) work well on Arch, I'll keep that target around with the changes you suggested.

**Comment by Celti** [comment]
Ah — if you're *just* keeping `fpm` around for Arch, I'd instead suggest looking at how [quarry](https://github.com/anatol/quarry) handles packaging gems for Arch — or just submit a request for them to package kbsecret and not have to worry about it yourself.

**Comment by woodruffw** [comment]
I didn't know about quarry; this looks great.

In that case, I'll be removing all of the `fpm` builds. Thanks again!

**Comment by woodruffw** [comment]
Opened https://github.com/anatol/quarry/pull/81

**Comment by woodruffw** [comment]
@Celti Could you give `ruby-kbsecret` in `quarry` a try and let me know if there are any issues?

**Comment by woodruffw** [comment]
For any future contributors, here's an initial stab at a Snapcraft config:

```yaml
name: kbsecret
version: FIXME
summary: A secret manager backed by Keybase and KBFS
description: |
  KBSecret is a command line utility and Ruby library for managing secrets.
  Secrets can be structured (like login pairs and environment keys), or
  unstructured (like raw text or blobs of data). They can also be shared between
  multiple individuals or entire teams via the Keybase platform.
grade: devel
confinement: devmode

apps:
  kbsecret:
    environment:
      RUBYLIB: $SNAP/usr/lib/ruby/2.3.0:$SNAP/usr/lib/x86_64-linux-gnu/ruby/2.3.0
      GEM_HOME: $SNAP/gems
      GEM_PATH: $SNAP
    command: ruby $SNAP/bin/kbsecret

parts:
  kbsecret:
    plugin: nil
    source: git://github.com/kbsecret/kbsecret.git
    build: gem build kbsecret.gemspec
    install: gem install kbsecret-*.gem --config-file /dev/null -i $SNAPCRAFT_PART_INSTALL
    build-packages: [gcc, libc6-dev, make, ruby-dev]
    stage-packages: [ruby]
```

This would ideally not be tied to Ruby 2.3 and would be generated by a script, so that `version` could be filled in.
